roles:
  - name: spotify
    src: git+https://github.com/johnnycederholm/ansible-role-spotify.git
    version: main
  - name: docker-engine
    src: git+git@github.com:johnnycederholm/ansible-role-docker-engine.git
    version: main
  - name: drawio
    src: git+git@github.com:johnnycederholm/ansible-role-drawio.git
    version: main
  - name: google-chrome
    src: git+git@github.com:johnnycederholm/ansible-role-google-chrome.git
    version: main
  - name: dotnet-sdk
    src: git+git@github.com:johnnycederholm/ansible-role-dotnet-sdk.git
    version: main
  - name: vs-code
    src: git+git@github.com:johnnycederholm/ansible-role-vs-code.git
    version: main
  - name: powershell
    src: git+git@github.com:johnnycederholm/ansible-role-powershell.git
    version: main
  - name: obsidian
    src: git+git@github.com:johnnycederholm/ansible-role-obsidian.git
    version: main
  - name: plymouth
    src: git+git@github.com:johnnycederholm/ansible-role-plymouth.git
    version: main